# arxivの学問領域の指定
subject: 'cat:cs.*'

# 検索キーワード
keywords:
        traversability: 5
        autonomous driving: 2
        cost map: 4
        SLAM: 3
        localization: 2
        denoising: 2
        RVIN: 3
        color quantization: 4
        saliency: 1
        perturbation: 1
        adversarial perturbation: 4
        image generation: 1
        image: 1
        sound: 1
        audio: 1
        computer: 1
# mixture of experts: 2
# multiple choice learning: 2        
# multi choice learning: 2       

# 通知の閾値
score_threshold: 0
