name: Carrier Owl

on:
  schedule:
    # github actions のデフォルトの time zone が UTC なので、日本時間 - 9時間 した値を書く
    # 分 時 日 月 曜日
    - cron: "0 9 * * *"
  workflow_dispatch:

  push:
    branches:
      - test-send-to-slack

jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Run image
        uses: abatilo/actions-poetry@v2.1.6
        with:
          poetry-version: 1.4.1

      - name: install dependencies
        run: poetry install

      - name: Run owl
        run: poetry run python src/carrier_owl.py
        env:
          SLACK_ID: ${{ secrets.SLACK_ID }}
          LINE_TOKEN: ${{ secrets.LINE_TOKEN }}
